cc=g++
CFLAGS=-g 

all : exo1.out exo2.out exo3.out


exo1.out : exo1.cpp
	$(cc) $(CFLAGS)  -o $@ $<

exo2.out : exo2.cpp
	$(cc) $(CFLAGS)  -o $@ $<

exo3.out : exo3.cpp
	$(cc) $(CFLAGS)  -o $@ $<

clear :
	rm *.out